# NumPy: estructuras matriciales

[NumPy](https://numpy.org/) es una librería Python que posibilita el trabajar con vectores, matrices y arreglos N-dimensionales de manera eficiente.

In [3]:
import numpy as np

## Definiendo vectores (arreglos unidimensionales)

Para definir vectores y matrices NumPy dispone de la función `array`, la cual recibe como argumento de entrada una lista de valores y/o una lista que contenga listas anidadas. 

De manera específica, para definir un arreglo unidimensional (vector), debemos pasar una lista de valores, por ejemplo:

In [17]:
x = np.array([1,2,3,5,6,7,8,9,10])

Ese arreglo definido podemos usarlo en operaciones aritméticas y éstas se realizarán elemento a elemento, por ejemplo:

In [18]:
2*x

array([ 2,  4,  6, 10, 12, 14, 16, 18, 20])

Lo anterior multiplica cada valor contenido en el vector `x` por el valor numérico correspondiente. Algunos otros ejemplos:

In [19]:
x + 2

array([ 3,  4,  5,  7,  8,  9, 10, 11, 12])

In [20]:
x**2

array([  1,   4,   9,  25,  36,  49,  64,  81, 100], dtype=int32)

Incluso podemos aplicar algunas funciones matemáticas contenidas en NumPy, por ejemplo:

In [21]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        , 3.16227766])

In [22]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.95892427, -0.2794155 ,
        0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

### La función `linspace`

La función `linspace` se utiliza para definir un arreglo unidimensional de N-elementos linealmente equiespaciados entre dos valores límites especificados, por ejemplo:

In [24]:
y = np.linspace(0, 10)
y

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

La instrucción anterior crea un vector `y` con 50 valores numéricos entre 0 y 10. Si queremos establecer la cantidad de elementos, debemos introducir un tercer argumento que indique la cantidad de elementos:

In [27]:
z = np.linspace(0, 10, 11)
z

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])