# NumPy: estructuras matriciales

[NumPy](https://numpy.org/) es una librería de Python que posibilita el trabajar con vectores, matrices y arreglos N-dimensionales de manera eficiente.

Para el resto del capítulo se asumirá que previo a cualquier código se habrá importado la librería NumPy utilizando el *alias* `np`, como sigue:

In [1]:
import numpy as np

## Una introducción al `array` de NumPy

Para definir vectores y matrices, NumPy dispone de la función `array`, la cual recibe como argumento de entrada una lista de valores y/o una lista que contenga listas anidadas. La función `array` crea un objeto de la clase `ndarray`. Los objetos de la clase `ndarray` son la estructura básica de NumPy.

## Arreglos unidimensionales (Vectores)

Para definir un arreglo unidimensional (vector), debemos pasar una lista de valores (usualmente numéricos), por ejemplo:

In [2]:
x = np.array([1,2,3,5,6,7,8,9,10])

In [3]:
type(x)

numpy.ndarray

El arreglo definido anteriormente podemos usarlo en operaciones aritméticas, y éstas se realizarán elemento a elemento, por ejemplo:

In [4]:
2*x

array([ 2,  4,  6, 10, 12, 14, 16, 18, 20])

Lo anterior multiplica cada valor contenido en el vector `x` por el valor numérico correspondiente. Enseguida se muestran algunos otros ejemplos:

In [5]:
x + 2

array([ 3,  4,  5,  7,  8,  9, 10, 11, 12])

In [6]:
x**2

array([  1,   4,   9,  25,  36,  49,  64,  81, 100], dtype=int32)

Incluso podemos aplicar algunas funciones matemáticas que forman parte de NumPy, por ejemplo:

In [7]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        , 3.16227766])

In [8]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.95892427, -0.2794155 ,
        0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

### La función `linspace`

La función `linspace` se utiliza para definir un arreglo unidimensional de N-elementos linealmente equiespaciados entre dos valores límites especificados, por ejemplo:

In [9]:
y = np.linspace(0, 10)
y

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

La instrucción anterior crea un vector `y` con 50 valores numéricos entre 0 y 10. Si queremos establecer la cantidad de elementos, debemos introducir un tercer argumento que indique la cantidad de elementos:

In [10]:
z = np.linspace(0, 10, 11)
z

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

El arreglo `z` que resulta contiene 11 elementos entre 0 y 10. 

### La función `arange`

La función `arange` crea un arreglo unidimensional entre dos valores límites, utilizando un paso (o incremento) especificado. La sintaxis más general de `arange` es como sigue:

```python
np.arange(start, stop, step)
```

Donde `start` es el valor límite inferior, `stop` el valor límite superior y `step` el paso. Observa el siguiente ejemplo:

In [26]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Podemos notar que el arreglo resultante incluye el valor límite inferior (`start`), pero no incluye el valor límite superior (`stop`); se debe tener mucho cuidado con este aspecto. Por defecto, el paso de la función `arange` es de 1, es decir, la instrucción anterior también se pudo haber indicado como sigue:

In [27]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

La función `arange` también se puede invocar utilizando un argumento:

In [28]:
np.arange(5)

array([0, 1, 2, 3, 4])

En este caso se asume que el valor pasado como argumento corresponde a `stop`, y por defecto se asume que `start=0` y `step=1`.

## Matrices

En NumPy, con la función `array`, se pueden definir y manipular matrices. Para crear matrices se debe pasar como argumento una lista de listas, donde cada sublista es una fila de la matriz. Por ejemplo vamos a suponer que se requiere crear la siguiente matriz $A$:

$$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$$

En NumPy se definiría de la siguiente manera:

In [30]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Podemos observar que cada sublista corresponde, efectivamente, a cada fila de la matriz. Debe cuidarse que cada sublista contenga exactamente el mismo número de elementos, de lo contrario la definición ya no correspondería a una matriz numérica, sino a un simple arreglo de arreglos.

### Operaciones básicas

Para los propósitos de este texto, llamaremos operaciones básicas con matrices a la suma, resta y multiplicación de matrices. Supongamos cuatro matrices $A$, $B$, $C$ y $D$, definidas como sigue:

$$
A = \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
\quad ; \quad
B = \begin{bmatrix}
5 & 0 \\
-8 & 3 \\
\end{bmatrix}
\quad ; \quad
C = \begin{bmatrix}
11 & 4 & 9 \\
0 & 1 & -4 
\end{bmatrix}
\quad ; \quad
D = \begin{bmatrix}
-5 & 6 \\
2 & 3 \\
12 & 1 
\end{bmatrix}
$$

Para crearlas en NumPy haríamos lo siguiente:

In [43]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,0],[-8,3]])
C = np.array([[11,4,9],[0,1,-4]])
D = np.array([[-5,6],[2,3],[12,1]])

Para sumar matrices utilizamos el operador `+`, por ejemplo, para calcular $A+B$:

In [45]:
A + B # suma de matrices

array([[ 6,  2],
       [-5,  7]])

Debemos recordar que la suma (y resta) de matrices es una operación que se realiza elemento a elemento, esto implica que las matrices involucradas deben ser del mismo tamaño. Si intentamos realizar una suma con matrices de diferente tamaño ($A+C$), entonces Python nos devolverá un mensaje de error:

In [48]:
A + C

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

Como podemos observar Python lanza un `ValueError` y es muy explícito al indicar que dicha operación no se puede ejecutar con arreglos de ese tamaño.

La resta de matrices funciona de manera muy similar, con la consideración de que el operador involucrado en este caso es `-`:

In [50]:
A - B

array([[-4,  2],
       [11,  1]])

In [51]:
B - A

array([[  4,  -2],
       [-11,  -1]])

La multiplicación de una matriz por un escalar se puede ejecutar utilizando el operador `*`, por ejemplo:

In [53]:
5 * D

array([[-25,  30],
       [ 10,  15],
       [ 60,   5]])

Naturalmente, se pueden formar expresiones que combinen la multiplicación por un escalar y la suma/resta matricial, por ejemplo si quisiéramos calcular $3A + 10B$, se tendría:

In [54]:
3*A + 10*B

array([[ 53,   6],
       [-71,  42]])

Para la multiplicación matricial se puede utilizar el operador `@`. En la siguiente línea se calcula el producto matricial $AB$:

In [56]:
A @ B # multiplicación matricial

array([[-11,   6],
       [-17,  12]])

Otra manera de efectuar una multiplicación de matrices es utilizando la función `matmul`:

In [59]:
np.matmul(A,B)

array([[-11,   6],
       [-17,  12]])

Como es esperable, las reglas del álgebra de matrices se aplican al momento de efectuar la multiplicación de matrices, así que por ejemplo, no es lo mismo calcular $DC$ que $CD$.

In [64]:
D @ C

array([[-55, -14, -69],
       [ 22,  11,   6],
       [132,  49, 104]])

In [65]:
C @ D

array([[ 61,  87],
       [-46,  -1]])

```{warning}
El operador `*` cuando se aplica a dos estructuras matriciales no devuelve el producto matricial, sino que calcula una multiplicación elemento a elemento.
```

In [69]:
A * B

array([[  5,   0],
       [-24,  12]])

In [70]:
A @ B

array([[-11,   6],
       [-17,  12]])

### Matriz tranpuesta, determinante y matriz inversa

La matriz inversa de una matriz dada se puede calcular utilizando la función

In [71]:
from numpy.linalg import inv, det

In [72]:
inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [73]:
inv(B)

array([[ 2.00000000e-01, -6.93889390e-18],
       [ 5.33333333e-01,  3.33333333e-01]])

In [74]:
inv(A) @ A

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [75]:
# np.set_printoptions(suppress=True)