# NumPy: estructuras matriciales

[NumPy](https://numpy.org/) es una librería de Python que posibilita el trabajar con vectores, matrices y arreglos N-dimensionales de manera eficiente.

Para el resto del capítulo se asumirá que previo a cualquier código se habrá importado la librería NumPy utilizando el *alias* `np`, como sigue:

In [6]:
import numpy as np

## El `array` de NumPy

Para definir vectores y matrices, NumPy dispone de la función `array`, la cual recibe como argumento de entrada una lista de valores y/o una lista que contenga listas anidadas. La función `array` crea un objeto de la clase `ndarray`. Los objetos de la clase `ndarray` son la estructura básica de NumPy.

### Arreglos unidimensionales (Vectores)

Para definir un arreglo unidimensional (vector), debemos pasar una lista de valores (usualmente numéricos), por ejemplo:

In [22]:
x = np.array([1,2,3,5,6,7,8,9,10])

In [23]:
type(x)

numpy.ndarray

El arreglo definido anteriormente podemos usarlo en operaciones aritméticas, y éstas se realizarán elemento a elemento, por ejemplo:

In [24]:
2*x

array([ 2,  4,  6, 10, 12, 14, 16, 18, 20])

Lo anterior multiplica cada valor contenido en el vector `x` por el valor numérico correspondiente. Algunos otros ejemplos:

In [25]:
x + 2

array([ 3,  4,  5,  7,  8,  9, 10, 11, 12])

In [26]:
x**2

array([  1,   4,   9,  25,  36,  49,  64,  81, 100], dtype=int32)

Incluso podemos aplicar algunas funciones matemáticas que forman parte de NumPy, por ejemplo:

In [27]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        , 3.16227766])

In [28]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.95892427, -0.2794155 ,
        0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

#### La función `linspace`

La función `linspace` se utiliza para definir un arreglo unidimensional de N-elementos linealmente equiespaciados entre dos valores límites especificados, por ejemplo:

In [29]:
y = np.linspace(0, 10)
y

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

La instrucción anterior crea un vector `y` con 50 valores numéricos entre 0 y 10. Si queremos establecer la cantidad de elementos, debemos introducir un tercer argumento que indique la cantidad de elementos:

In [30]:
z = np.linspace(0, 10, 11)
z

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

El arreglo `z` que resulta contiene 11 elementos entre 0 y 10. 

#### La función `arange`

La función `arange` crea un arreglo unidimensional entre dos valores límites, utilizando un paso (o incremento) especificado. La sintaxis más general de `arange` es como sigue:

```python
np.arange(start, stop, step)
```

Donde `start` es el valor límite inferior, `stop` el valor límite superior y `step` el paso. Observa el siguiente ejemplo:

In [43]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Podemos notar que el arreglo resultante incluye el valor límite inferior (`start`), pero no incluye el valor límite superior (`stop`); se debe tener mucho cuidado con este aspecto. Por defecto, el paso de la función `arange` es de 1, es decir, la instrucción anterior también se pudo haber indicado como sigue:

In [45]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

La función `arange` también se puede invocar utilizando un argumento:

In [46]:
np.arange(5)

array([0, 1, 2, 3, 4])

En este caso se asume que el valor pasado como argumento corresponde a `stop`, y por defecto se asume que `start=0` y `step=1`.

### Matrices

#### Operaciones básicas

In [47]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A,B, sep="\n\n")

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [48]:
A + B # suma

array([[ 6,  8],
       [10, 12]])

In [49]:
A - B # resta

array([[-4, -4],
       [-4, -4]])

In [50]:
A @ B # multiplicación matricial

array([[19, 22],
       [43, 50]])

In [51]:
B @ A # multiplicación matricial

array([[23, 34],
       [31, 46]])

### Inversa y determinante

In [52]:
from numpy.linalg import inv, det

In [53]:
inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [54]:
inv(B)

array([[-4. ,  3. ],
       [ 3.5, -2.5]])

In [55]:
inv(A) @ A

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [56]:
# np.set_printoptions(suppress=True)

In [57]:
inv(A) @ A

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [42]:
det(B)

-1.999999999999999